[package]
name = "salsa-2022-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
heck = "0.4"
proc-macro2 = "1.0"
quote = "1.0"
eyre = "0.6.5"
syn = { version = "2.0.64", features = ["visit-mut"] }
