name: Test

on:
  push:
    branches:
    - master
    - staging
    - trying
  pull_request:
    paths:
    - '**.rs'
    - '**/Cargo.*'
    - '.github/workflows/**.yml'

jobs:
  test:
    name: Test
    strategy:
      matrix:
        rust:
        - stable
        - beta
        experimental:
        - false
        include:
        - rust: nightly
          experimental: true
    continue-on-error: ${{ matrix.experimental }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        components: rustfmt, clippy
        default: true
    - uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: -- --check
    - uses: actions-rs/cargo@v1
      with:
        command: clippy
    - uses: actions-rs/cargo@v1
      with:
        command: check
        args: --all
    - uses: actions-rs/cargo@v1
      with:
        command: test
        args: --all-features --all-targets
    - uses: actions-rs/cargo@v1
      with:
        command: test
        args: --all-features --all-targets --package salsa-2022-tests
    - uses: actions-rs/cargo@v1
      with:
        command: test
        args: --all-features --doc
    - uses: actions-rs/cargo@v1
      with:
        command: check
        args: --no-default-features
